[build]
builder = "NIXPACKS"
buildCommand = "npm install --legacy-peer-deps && node build.mjs"

[deploy]
startCommand = "node dist/index.mjs"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
