[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.install]
cmds = ["npm install -g pnpm", "pnpm install --ignore-scripts"]

[build.nixpacksPlan.phases.build]
cmds = ["cd artifacts/api-server && node build.mjs"]

[deploy]
startCommand = "cd artifacts/api-server && node --enable-source-maps dist/index.mjs"
